### ISSUE TITLE
pythreatgrid import error.. again..

### ISSUE THREAD

**Issue by deadbits** [Te-k/harpoon#108]
Same problem as #88 

I also tried to re-install both directly from `pip install pythreatgrid`, and by cloning the repo and then installing per the instructions for the pythreatgrid repo. 

Same problem :|

**harpoon config output with exception:**
```
‹master› » harpoon config
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python3.7/site-packages/harpoon-0.1.1-py3.7.egg/harpoon/main.py", line 31, in main
    plugins = init_plugins()
  File "/usr/local/lib/python3.7/site-packages/harpoon-0.1.1-py3.7.egg/harpoon/main.py", line 18, in init_plugins
    mod = __import__(plugin)
  File "/usr/local/lib/python3.7/site-packages/harpoon-0.1.1-py3.7.egg/harpoon/commands/domain.py", line 24, in <module>
    from pythreatgrid import ThreatGrid, ThreatGridError
ImportError: cannot import name 'ThreatGridError' from 'pythreatgrid' (/usr/local/lib/python3.7/site-packages/pythreatgrid/__init__.py)
```

**Comment by Te-k** [comment]
Hi, 
Thanks for opening the bug. I had to change the name of the package to [pythreatgrid2](https://github.com/Te-k/pythreatgrid2) because `pythreatgrid` was already used in pypi. So it is a bit stupid but it breaks the dependences. To solve it, you need to download the last version of harpoon, and just a `pip install .` should solve this. If you have any other issue, please remove pythreadgrid manually and  install pythreatgrid2 manually. 
Sorry about that, I hope to have soon a better way to do updates, but I need to have the two missing packages in pypi first, which may be hard for some reasons

**Comment by Te-k** [comment]
Closing for now, feel free to reopen if it is still an issue
